name = "LinearOperatorCollection"
uuid = "a4a2c56f-fead-462a-a3ab-85921a5f2575"
authors = ["Tobias Knopp <tobias.knopp@tuhh.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
