name = "LinearOperatorCollection"
uuid = "a4a2c56f-fead-462a-a3ab-85921a5f2575"
authors = ["Tobias Knopp <tobias.knopp@tuhh.de> and contributors"]
version = "1.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[weakdeps]
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"

[extensions]
LinearOperatorWaveletExt = "Wavelets"
LinearOperatorFFTWExt = "FFTW"
LinearOperatorNFFTExt = ["NFFT", "FFTW"]

[compat]
julia = "1.9"
FFTW = "1.0"
LinearOperators = "2.3.3"
Reexport = "1.0"
Wavelets = "0.9, 0.10"
NFFT = "0.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FFTW", "Wavelets", "NFFT"]
