steps:
  - label: "Nvidia GPUs -- LinearOperators.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project -e '
      using Pkg
      Pkg.add("CUDA")
      Pkg.add("CuNFFT")
      Pkg.add("JLArrays")
      Pkg.add("NFFT")
      Pkg.add("Wavelets")
      Pkg.add("FFTW")
      Pkg.add("RadonKA")
      Pkg.instantiate()
      include("test/gpu/cuda.jl")'
    timeout_in_minutes: 30